# .github/release.yml

changelog:
  exclude:
    labels:
      - ci
      - test
      - chore
  categories:
    - title: Exciting New Features 🎉
      labels:
        - feat
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Bug Fixes 🐛
      labels:
        - fix
    - title: Enhancements 🔧
      labels:
        - refactor
        - perf
        - enhancement
        - enhance
    - title: Other Changes 🚧
      labels:
        - "*"
