name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '*.md'

env:
  CLOJURE_VERSION: '1.10.1.727'
  JAVA_VERSION: '1.8'
  # This is the latest node version of we can run.
  NODE_VERSION: '16'

jobs:

  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: 'true'

      - name: Clojure cache
        uses: actions/cache@v2
        id: clojure-deps
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clojure-deps-${{ hashFiles('deps.edn') }}
          restore-keys: ${{ runner.os }}-clojure-deps-

      - name: Prepare Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Clojure tools.deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: ${{ env.CLOJURE_VERSION }}

      - name: Fetch Clojure deps
        if: steps.clojure-deps.outputs.cache-hit != 'true'
        run: clojure -A:cljs -P

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('package.json') }}-${{ hashFiles('resources/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn--
      - name: Fetch yarn deps
        run: yarn install

      - name: Project shadow-cljs compiler cache
        uses: actions/cache@v2
        with:
          path: .shadow-cljs
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-

      - name: Run ClojureScript test
        run: |
          yarn cljs:test
          node static/tests.js

      - name: Prepare E2E test build
        run: |
          yarn release
          (cd static && yarn install && yarn rebuild:better-sqlite3)

      - name: Run Playwright test
        run: xvfb-run -- yarn e2e-test
        env:
          DEBUG: "pw:test"

      - name: Save test artifacts
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-report
          path: artifacts.zip
